#!/bin/bash
echo" ''''disable selinux''''"
Setenforce 0
 sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config && cat /etc/selinux/config
sleep 2

systemctl stop firewalld
systemctl disable firewalld

yum install git -y
yum install net-tools -y 
yum install epel-release -y 
yum -y install jq avahi

git clone https://github.com/tiedoll95/docker

chmod 777 /$PWD/docker
sh /$PWD/docker/install-docker

curl -sL "https://raw.githubusercontent.com/home-assistant/hassio-installer/master/hassio_install.sh" | bash -s

ip addr show ens33 | grep "inet\b" | awk '{print $2}' | cut -d'/' -f1 >> /tmp/interface

echo "#################################################################"
echo "#################################################################"
echo -e '\E[32m'"Login with: http://"$interface":8123"
echo "#################################################################"
echo "#################################################################"
